# Generated by Django 2.2.1 on 2019-07-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='BAIRRO')),
                ('nomeCidade', models.CharField(max_length=50, verbose_name='NOME CIDADE')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='TIPO TELEFONE')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='NOME')),
                ('sobreNome', models.CharField(max_length=50, verbose_name='SOBRENOME')),
                ('cpf', models.CharField(max_length=11, verbose_name='cpf')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('nomeRua', models.CharField(max_length=50, verbose_name='NOME RUA')),
                ('numero', models.CharField(max_length=10, verbose_name='NÚMERO')),
                ('complemento', models.CharField(max_length=50, verbose_name='COMPLEMENTO')),
                ('idBairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Bairro', verbose_name='BAIRRO')),
            ],
        ),
    ]
