# Generated by Django 2.1.7 on 2019-11-18 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='default.png', upload_to='fotosUsuario/')),
                ('idPessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA')),
            ],
        ),
    ]
