# Generated by Django 2.2.3 on 2019-07-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='idBairro',
        ),
        migrations.DeleteModel(
            name='TipoTelefone',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
