# Generated by Django 2.1.7 on 2019-11-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_fotousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotousuario',
            name='foto',
            field=models.ImageField(default='avatar_2x.png', upload_to='fotosUsuario/'),
        ),
    ]
