# Generated by Django 2.2.3 on 2019-08-01 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_telefone_tipotelefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEstado', models.CharField(max_length=20, verbose_name='NOME ESTADO')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeMunicipio', models.CharField(max_length=20, verbose_name='NOME MUNICIPIO')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Estado', verbose_name='NOME ESTADO')),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBairro', models.CharField(max_length=20, verbose_name='NOME BAIRRO')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Municipio', verbose_name='NOME MUNICIPIO')),
            ],
        ),
    ]
