# Generated by Django 2.2.3 on 2019-08-06 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_bairro_estado_municipio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'verbose_name': 'Bairro', 'verbose_name_plural': 'Bairros'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'verbose_name': 'Telefone', 'verbose_name_plural': 'Telefones'},
        ),
        migrations.AlterModelOptions(
            name='tipotelefone',
            options={'verbose_name': 'TipoTelefone', 'verbose_name_plural': 'TipoTelefones'},
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepRua', models.CharField(max_length=20, verbose_name='CEP RUA')),
                ('nomeRua', models.CharField(max_length=20, verbose_name='NOME RUA')),
                ('idBairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Bairro', verbose_name='NOME BAIRRO')),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
    ]
