# Generated by Django 2.2.4 on 2019-08-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20190829_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.IntegerField(verbose_name='NÚMERO'),
        ),
    ]
