# Generated by Django 2.2.4 on 2019-08-22 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuario', '0005_auto_20190806_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField(max_length=8, verbose_name='CEP')),
                ('enderecoNumero', models.CharField(max_length=11, verbose_name='NÚMERO')),
                ('complemento', models.CharField(max_length=45, verbose_name='COMPLEMENTO')),
                ('observacao', models.CharField(max_length=45, verbose_name='OBSERVAÇÃO')),
                ('municipio', models.CharField(max_length=45, verbose_name='MUNICIPIO')),
                ('estado', models.CharField(max_length=2, verbose_name='ESTADO')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=45, verbose_name='LOGRADOURO')),
                ('bairro', models.CharField(max_length=45, verbose_name='BAIRRO')),
            ],
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='idEstado',
        ),
        migrations.RemoveField(
            model_name='rua',
            name='idBairro',
        ),
        migrations.DeleteModel(
            name='Bairro',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='Rua',
        ),
        migrations.AddField(
            model_name='endereco',
            name='idLogradouro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Logradouro', verbose_name='LOGRADOURO'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='idPessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PESSOA'),
        ),
    ]
