# Generated by Django 2.2.4 on 2019-09-13 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeOrgao', models.CharField(max_length=45, verbose_name='NOME ORGÃO')),
                ('descricao', models.CharField(max_length=100, verbose_name='DESCRIÇÃO')),
                ('emailOrgao', models.CharField(max_length=45, verbose_name='EMAIL ORGÃO')),
                ('nomeResponsavelOrgao', models.CharField(max_length=45, verbose_name='RESPONSÁVEL PELO ÓRGÃO')),
                ('enderecoOrgao', models.CharField(default='', max_length=45, verbose_name='ENDERECO ORGÃO')),
                ('telefoneOrgao', models.CharField(default='', max_length=45, verbose_name='TELEFONE ORGÃO')),
            ],
            options={
                'verbose_name': 'Orgao',
                'verbose_name_plural': 'Orgao',
            },
        ),
        migrations.CreateModel(
            name='TipoLotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'verbose_name': 'TipoLotacao',
                'verbose_name_plural': 'TiposLotacao',
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=45, verbose_name='OBSERVAÇÃO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ÓRGÃO')),
                ('idTipoLotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.TipoLotacao', verbose_name='TIPO LOTAÇÃO')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
            options={
                'verbose_name': 'Lotacao',
                'verbose_name_plural': 'Lotacao',
            },
        ),
    ]
