# Generated by Django 2.2.4 on 2019-09-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0005_auto_20190830_0851'),
        ('Chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeOrgao', models.CharField(max_length=45, verbose_name='nomeOrgao')),
                ('descricao', models.CharField(max_length=100, verbose_name='descricao')),
                ('emailOrgao', models.CharField(max_length=45, verbose_name='emailOrgao')),
                ('nomeResponsavelOrgao', models.CharField(max_length=45, verbose_name='nomeResponsavelOrgao')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Endereco', verbose_name='ENDERECO ORGAO')),
                ('idTelefone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Telefone', verbose_name='TELEFONE ORGAO')),
                ('idTipoChamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.TipoChamado', verbose_name='TIPO CHAMADO')),
            ],
            options={
                'verbose_name': 'Orgao',
                'verbose_name_plural': 'Orgao',
            },
        ),
    ]
