# Generated by Django 2.2.4 on 2019-09-03 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orgao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'verbose_name': 'TipoLotacao',
                'verbose_name_plural': 'TiposLotacao',
            },
        ),
        migrations.AlterField(
            model_name='orgao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='DESCRIÇÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='emailOrgao',
            field=models.CharField(max_length=45, verbose_name='EMAIL ORGÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nomeOrgao',
            field=models.CharField(max_length=45, verbose_name='NOME ORGÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nomeResponsavelOrgao',
            field=models.CharField(max_length=45, verbose_name='RESPONSÁVEL PELO ÓRGÃO'),
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=45, verbose_name='OBSERAÇÃO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ÓRGÃO')),
                ('idTipoLotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.TipoLotacao', verbose_name='TIPO LOTAÇÃO')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
            options={
                'verbose_name': 'Lotacao',
                'verbose_name_plural': 'Lotacao',
            },
        ),
    ]
