# Generated by Django 2.2.4 on 2019-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgao',
            name='telefoneOrgao',
            field=models.IntegerField(verbose_name='TELEFONE ORGÃO'),
        ),
    ]
