# Generated by Django 2.2.4 on 2019-09-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0002_auto_20190913_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipolotacao',
            options={'permissions': (('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')), 'verbose_name': 'TipoLotacao', 'verbose_name_plural': 'TiposLotacao'},
        ),
    ]
