# Generated by Django 2.2.4 on 2019-09-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0003_auto_20190904_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgao',
            name='idEndereco',
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='idTelefone',
        ),
    ]
