# Generated by Django 2.2.4 on 2019-09-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0003_auto_20190917_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipolotacao',
            options={'verbose_name': 'TipoLotacao', 'verbose_name_plural': 'TiposLotacao'},
        ),
    ]
