# Generated by Django 2.2.4 on 2019-09-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0004_auto_20190909_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='enderecoOrgao',
            field=models.CharField(default='', max_length=45, verbose_name='ENDERECO ORGÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nomeResponsavelOrgao',
            field=models.CharField(default='', max_length=45, verbose_name='RESPONSÁVEL PELO ÓRGÃO'),
        ),
    ]
