# Generated by Django 2.2.4 on 2019-09-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0005_auto_20190909_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgao',
            name='telefoneOrgao',
            field=models.CharField(default='', max_length=45, verbose_name='TELEFONE ORGÃO'),
        ),
        migrations.AlterField(
            model_name='orgao',
            name='nomeResponsavelOrgao',
            field=models.CharField(max_length=45, verbose_name='RESPONSÁVEL PELO ÓRGÃO'),
        ),
    ]
