# Generated by Django 2.2.4 on 2019-09-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orgao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoTipoChamado', models.CharField(max_length=45, verbose_name='TIPO CHAMADO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ORGÃO')),
            ],
            options={
                'verbose_name': 'TipoChamados',
                'verbose_name_plural': 'TipoChamados',
            },
        ),
    ]
