# Generated by Django 2.2.5 on 2019-11-11 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
        ('Orgao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAbertura', models.DateField(auto_now_add=True, verbose_name='ABERTO EM')),
                ('dataConclusao', models.DateField(auto_now=True, verbose_name='CONCLUÍDO EM')),
                ('numeroProtocolo', models.CharField(blank=True, max_length=45, null=True, verbose_name='NÚMERO DE PROTOCOLO')),
                ('observacao', models.CharField(max_length=100, verbose_name='OBSERVAÇÃO')),
                ('observacaoOrgao', models.CharField(blank=True, max_length=100, null=True, verbose_name='RETORNO DO ÓRGÃO')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Endereco', verbose_name='ENDEREÇO DO CHAMADO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ORGÃO')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TipoChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoTipoChamado', models.CharField(max_length=45, verbose_name='TIPO CHAMADO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ORGÃO')),
            ],
            options={
                'verbose_name': 'TipoChamados',
                'verbose_name_plural': 'TipoChamados',
            },
        ),
        migrations.CreateModel(
            name='OcorrenciasChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoOcorrenciasChamado', models.CharField(max_length=45, verbose_name='DESCRIÇÃO DE OCORRENCIAS DE CHAMADO')),
                ('idChamado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Chamados.Chamado', verbose_name='CHAMADO')),
            ],
            options={
                'verbose_name': 'OcorrenciasChamado',
                'verbose_name_plural': 'OcorrenciasChamado',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='idStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.Status', verbose_name='STATUS'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='idTipoChamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.TipoChamado', verbose_name='TIPO DE CHAMADO'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO'),
        ),
    ]
