# Generated by Django 2.2.4 on 2019-09-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orgao', '0004_auto_20190917_1105'),
        ('Chamados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciasChamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoOcorrenciasChamado', models.CharField(max_length=45, verbose_name='DESCRIÇÃO DE OCORRENCIAS DE CHAMADO')),
            ],
            options={
                'verbose_name': 'OcorrenciasChamado',
                'verbose_name_plural': 'OcorrenciasChamado',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=45, verbose_name='DESCRIÇÃO')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAbertura', models.DateField(auto_now_add=True, verbose_name='ABERTO EM')),
                ('dataConclusao', models.DateField(auto_now=True, verbose_name='CONCLUÍDO EM')),
                ('numeroProtocolo', models.CharField(max_length=45, verbose_name='NÚMERO DE PROTOCOLO')),
                ('observacao', models.CharField(max_length=100, verbose_name='OBSERVAÇÃO')),
                ('observacaoOrgao', models.CharField(blank=True, max_length=100, null=True, verbose_name='RETORNO DO ÓRGÃO')),
                ('idEndereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Endereco', verbose_name='ENDEREÇO DO CHAMADO')),
                ('idOcorrenciasChamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.OcorrenciasChamado', verbose_name='OCORRENCIAS DO CHAMADO')),
                ('idOrgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ORGÃO')),
                ('idStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.Status', verbose_name='STATUS')),
                ('idTipoChamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chamados.TipoChamado', verbose_name='TIPO DE CHAMADO')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USUÁRIO')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
