# Generated by Django 2.2.4 on 2019-09-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orgao', '0003_auto_20190904_0937'),
        ('Chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipochamado',
            name='idOrgao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Orgao.Orgao', verbose_name='ORGÃO'),
            preserve_default=False,
        ),
    ]
