# Generated by Django 2.1.7 on 2019-09-24 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chamados', '0002_chamado_ocorrenciaschamado_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='idOcorrenciasChamado',
        ),
        migrations.AddField(
            model_name='ocorrenciaschamado',
            name='idChamado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Chamados.Chamado', verbose_name='CHAMADO'),
        ),
    ]
