# Generated by Django 2.1.7 on 2019-09-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chamados', '0003_auto_20190923_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='numeroProtocolo',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='NÚMERO DE PROTOCOLO'),
        ),
    ]
